[workspace]

resolver = "2"

members = [
    "common",
    "dmntk",
    "evaluator",
    "examples",
    "feel",
    "feel-grammar",
    "feel-evaluator",
    "feel-number",
    "feel-parser",
    "feel-temporal",
    "gendoc",
    "macros",
    "model",
    "model-evaluator",
    "recognizer",
    "server",
    "workspace"
]

[workspace.package]
version = "0.3.5"
authors = ["Dariusz Depta <depta@engos.de>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.5.1"
base64 = "0.22.0"
chrono = "0.4.37"
chrono-tz = "0.9.0"
convert_case = "0.6.0"
clap = { version = "4.5.4", features = ["cargo"] }
dfp-number-sys = "0.1.0"
difference = "2.0.0"
domrs = "0.0.5"
markdown = "1.0.0-alpha.16"
once_cell = "1.19.0"
petgraph = "0.6.4"
quote = "1.0.36"
regex = "1.10.4"
reqwest = { version = "0.12.3", default-features = false, features = ["blocking", "json", "rustls-tls"] }
roxmltree = "0.19.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
syn = "2.0.59"
uuid = { version = "1.8.0", features = ["v4"] }
uriparse = "0.6.4"
url = "2.5.0"
urlencoding = "2.1.3"
walkdir = "2.5.0"
dmntk-common = "0.3.5"
dmntk-evaluator = "0.3.5"
dmntk-examples = "0.3.5"
dmntk-feel = "0.3.5"
dmntk-feel-evaluator = "0.3.5"
dmntk-feel-grammar = "0.3.5"
dmntk-feel-number = "0.3.5"
dmntk-feel-parser = "0.3.5"
dmntk-feel-temporal = "0.3.5"
dmntk-gendoc = "0.3.5"
dmntk-macros = "0.3.5"
dmntk-model = "0.3.5"
dmntk-model-evaluator = "0.3.5"
dmntk-recognizer = "0.3.5"
dmntk-server = "0.3.5"
dmntk-workspace = "0.3.5"
