[workspace]

resolver = "2"

members = [
    "common",
    "dmntk",
    "evaluator",
    "examples",
    "feel",
    "feel-grammar",
    "feel-evaluator",
    "feel-number",
    "feel-parser",
    "feel-temporal",
    "gendoc",
    "macros",
    "model",
    "model-evaluator",
    "recognizer",
    "server",
    "workspace"
]

[workspace.package]
version = "0.3.2"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.5.1"
base64 = "0.22.0"
chrono = "0.4.35"
chrono-tz = "0.8.6"
convert_case = "0.6.0"
clap = { version = "4.5.3", features = ["cargo"] }
dfp-number-sys = "0.1.0"
difference = "2.0.0"
domrs = "0.0.5"
markdown = "1.0.0-alpha.16"
once_cell = "1.19.0"
petgraph = "0.6.4"
quote = "1.0.35"
regex = "1.10.4"
reqwest = { version = "0.12.2", default-features = false, features = ["blocking", "json", "rustls-tls"] }
roxmltree = "0.19.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.114"
syn = "2.0.55"
uuid = { version = "1.8.0", features = ["v4"] }
uriparse = "0.6.4"
url = "2.5.0"
urlencoding = "2.1.3"
walkdir = "2.5.0"
dmntk-common = { path = "./common" }
dmntk-evaluator = { path = "./evaluator" }
dmntk-examples = { path = "./examples" }
dmntk-feel = { path = "./feel" }
dmntk-feel-evaluator = { path = "./feel-evaluator" }
dmntk-feel-grammar = { path = "./feel-grammar" }
dmntk-feel-number = { path = "./feel-number" }
dmntk-feel-parser = { path = "./feel-parser" }
dmntk-feel-temporal = { path = "./feel-temporal" }
dmntk-gendoc = { path = "./gendoc" }
dmntk-macros = { path = "./macros" }
dmntk-model = { path = "./model" }
dmntk-model-evaluator = { path = "./model-evaluator" }
dmntk-recognizer = { path = "./recognizer" }
dmntk-server = { path = "./server" }
dmntk-workspace = { path = "./workspace" }